Repository handy-js/handy, pull requests merged in 2023-05, with the labels that each got.

#2 add the main
  main.js
Labels: enhancement, good first issue

#4 Create Auto Assign Worflow
  .github/workflows/auto-assign.yml
Labels: enhancement

#6 In the event
  .gitignore
  components/declarative.js
  components/imperative.js
  hooks/state.js
  hooks/updateDOM.js
  main.js
  syntax/DOM.js
  syntax/databinding.js
  syntax/events.js
  syntax/operateurs.js
Labels: enhancement

#10 Array manipulation methods
  constants/Sort.js
  syntax/array.js
Labels: enhancement

#11 list of useful math functions
  syntax/math.js
Labels: enhancement

#12 Creat String module
  syntax/string.js
Labels: enhancement

#14 short capitalize
  syntax/string.js
Labels: enhancement

#15 Update the array module structure
  syntax/array.js
Labels: duplicate, enhancement

#18 Update the hooks branch
  .gitignore
  components/declarative.js
  components/imperative.js
  constants/Sort.js
  syntax/array.js
  syntax/math.js
  syntax/string.js
Labels: duplicate

#20 Update Math module structure
  syntax/math.js
Labels: duplicate, enhancement

#21 update event module structure
  syntax/events.js
Labels: duplicate, enhancement

#23 update the DOM module structre
  syntax/DOM.js
Labels: duplicate, enhancement

#27 Create codeql.yml
  .github/workflows/codeql.yml
Labels: enhancement

#32 The Handy Core Packages
  .gitignore
  hooks/updateDOM.js
  htmlLogic/README.md
  main.js
  packages/core/.gitignore
  packages/core/README.md
  packages/core/hooks/state.js
  packages/core/index.js
  packages/core/lib/DOM.js
  packages/core/lib/databinding.js
  packages/core/lib/events.js
  packages/core/lib/htmlLogic.js
  packages/core/package-lock.json
  packages/core/package.json
  packages/core/rollup.config.js
  packages/handy/.gitignore
  packages/handy/LICENSE
  packages/handy/README.md
  packages/handy/dist/handy.min.cjs
  packages/handy/index.js
  packages/handy/lib/array.js
  packages/handy/lib/math.js
  packages/handy/lib/operators.js
  packages/handy/lib/string.js
  packages/handy/modules/Sort.js
  packages/handy/package-lock.json
  packages/handy/package.json
  packages/handy/rollup.config.js
  src/colors.js
  src/index.html
  syntax/array.js
  syntax/math.js
  syntax/operateurs.js
  syntax/string.js
Labels: enhancement

#35 update the handy pkg documentation 📃
  packages/handy/README.md
Labels: documentation

#36 update handy pkg docs
  packages/handy/README.md
Labels: documentation

#40 patch the pkg docs
  packages/handy/README.md
  packages/handy/package.json
Labels: documentation

#41 add findIndices method
  packages/handy/lib/string.js
Labels: enhancement

#43 Update auto-assign.yml
  .github/workflows/auto-assign.yml
Labels: duplicate

#45 List of the lib authors 👥✍🏻
  AUTHORS
Labels: 📃 documentation, 📣 announcements

#47 Refactor the string module to global typescript String module
  packages/handy/README.md
  packages/handy/lib/string.js
Labels: 👷‍♂️ build or construction, 🛠 refactorization

#50 Pkg handy patch
  packages/handy/dist/handy.min.cjs
  packages/handy/dist/handy.min.cjs.map
  packages/handy/dist/handy.min.js
  packages/handy/dist/handy.min.js.map
  packages/handy/lib/array.ts
  packages/handy/lib/string.ts
  packages/handy/package.json
Labels: ✨ enhancement, 📦 packages

#51 handy hashmap feature
  packages/handy/README.md
  packages/handy/dist/handy.min.cjs
  packages/handy/dist/handy.min.cjs.map
  packages/handy/dist/handy.min.js
  packages/handy/dist/handy.min.js.map
  packages/handy/index.ts
  packages/handy/lib/hashmap.ts
  packages/handy/package.json
Labels: ✨ enhancement, feature 🔮, 📦 packages

#52 Update AUTHORS
  AUTHORS
Labels: ⚙ config

#53 Update the handy pkg
  .github/workflows/auto-assign.yml
  packages/handy/dist/handy.min.cjs
  packages/handy/dist/handy.min.cjs.map
  packages/handy/dist/handy.min.js
  packages/handy/dist/handy.min.js.map
  packages/handy/lib/array.ts
  packages/handy/lib/math.ts
  packages/handy/lib/string.ts
  packages/handy/package.json
Labels: ✨ enhancement, 📦 packages
